### ISSUE TITLE
Using “level 1” through “level 6” does not seem to work as intended...

### ISSUE THREAD

**Issue by stantonlefort** [nickbreaton/homebridge-modern-forms#12]
I can access all the fan speed levels by specifying %’s or increase/decrease level, but when I ask Siri to set the fan to “level 1” it goes to 33%.  Same for “level 2”.  All other level commands go to 0%. 

Am I missing something?  Can I access all 6 speed levels?  Thanks,

Stan

**Comment by nickbreaton** [comment]
Hey @stantonlefort. As far as I can tell Homekit only supports the fan speed as a percentage. 

If you say a percentage that doesn't exactly map to a 1-6 step, Siri will round to the closest step. 

My assumption of what's happening is you say "Step 3" for example, Siri is interpreting that as 3% and rounding to 0%. 

Hopefully this can help narrow down what's happening for you. If you come across away to display it as steps in the Homekit app please let me know.

**Comment by stantonlefort** [comment]
@nickbreaton - thanks for the prompt response.  I believe you are correct, but will report anything I find.  

Even though it does level understand "levels", there is lots of controllability.  I was able to say do to multiple variations of:

- "Hey Siri, turn on the <Room> Fan to 33%."
- "Hey Siri, increase the speed for the <Room> Fan"
- "Hey Siri, increase the fan speed for the <Room> Fan"
- It also handled modifiers of a "a little" or "a lot", and responded to exact percentages mostly correct.
- Once it responded to a fan command, it impressively kept the fan context so I could just say "Hey Siri increase the fan speed" or "Het Siri turn off the fan" and it would do so only for that fan.

Also, it seems to know the fans as a set (without any grouping), so the following works across my 3 Modern Forms fans in different rooms:
- "Hey Siri, turn on all the fans to 17%".
- "Hey Siri, turn off all the fans."
- "Her Siri, turn on all of the fan lights to maximum."
- "Hey Siri, turn off all fo the fan lights."

Not perfect ... but very good and 99.99% better than no HomeKit integration.  Thanks for making this available!
Stan

**Comment by nickbreaton** [comment]
Okay great. Since there's no further action to take at the moment, I'm going to close this. If you come across anything please feel free to reopen.
