### ISSUE TITLE
Allow configuration to accept list of subnets to scan

### ISSUE THREAD

**Issue by nickbreaton** [nickbreaton/homebridge-modern-forms#2]
Currently we make the assumption that your fans will be in the same subnet as your device running Homebridge when attempting to auto discover fans. 

https://github.com/nickbreaton/homebridge-modern-forms/blob/f915708a4229966918d9b7dfbf424a74342572aa/src/platform.ts#L59-L61

It's already proven out that this does not work for all users. A user has requested to allow the configuration to accept a list of subnets to scan.

**Comment by subdigital** [comment]
Wanted to add my +1 for this. I isolate these devices on an IOT VLAN that is separate from homebridge.
